### ISSUE TITLE
As a learner, I want to have 24/7 access to my account so that I can learn on my own schedule.

### ISSUE THREAD

**Issue by jlcharette** [CSPS-EFPC-IT/gccampus#14]
**Description**
Enter any extra information which may be helpful.

**Acceptance Criteria**
Acceptance criteria eliminate doubt from your issues and are vital to include when writing your user stories. Remember to keep them in basic language that cannot be misinterpreted.

If you are unsure of what to write, all you need to do is to picture the boundaries of your user story, and what must be true in order for a story to be confirmed in working as intended.

**Comment by Suehehle** [comment]
I think this one should be removed as it is a requirement that applies to the entire site... Having 24/7 access... ?

**Comment by PatrickMessierGoC** [comment]
Exactly!
