### ISSUE TITLE
As an anonymous learner or a public learner, I want to see, engage with and navigate the contents of the home page using the Internet.

### ISSUE THREAD

**Issue by jlcharette** [CSPS-EFPC-IT/gccampus#18]
**Description**
Enter any extra information which may be helpful.

**Acceptance Criteria**
Acceptance criteria eliminate doubt from your issues and are vital to include when writing your user stories. Remember to keep them in basic language that cannot be misinterpreted.

If you are unsure of what to write, all you need to do is to picture the boundaries of your user story, and what must be true in order for a story to be confirmed in working as intended.

**Comment by PatrickMessierGoC** [comment]
Not a user story. This is a platform-wide requirement, that is "the platform must be publicly available via Internet. Thus, this issue is abandoned.
