### ISSUE TITLE
As learner, I want to watch videos on their own pages so that I can leave my feedback and look at learner comments.

### ISSUE THREAD

**Issue by jlcharette** [CSPS-EFPC-IT/gccampus#28]
**Description**
Enter any extra information which may be helpful.

**Acceptance Criteria**
Acceptance criteria eliminate doubt from your issues and are vital to include when writing your user stories. Remember to keep them in basic language that cannot be misinterpreted.

If you are unsure of what to write, all you need to do is to picture the boundaries of your user story, and what must be true in order for a story to be confirmed in working as intended.

**Comment by PatrickMessierGoC** [comment]
Sounds like a duplicate of #30. Simply clarify the user roles in #30.

**Comment by PatrickMessierGoC** [comment]
Abandoned as deemed a duplicate.
