### ISSUE TITLE
As a learner, I can access all content on a mobile device using a mobile browser.

### ISSUE THREAD

**Issue by jlcharette** [CSPS-EFPC-IT/gccampus#5]
**Description**
Enter any extra information which may be helpful.

**Acceptance Criteria**
Acceptance criteria eliminate doubt from your issues and are vital to include when writing your user stories. Remember to keep them in basic language that cannot be misinterpreted.

If you are unsure of what to write, all you need to do is to picture the boundaries of your user story, and what must be true in order for a story to be confirmed in working as intended.

**Comment by Suehehle** [comment]
This one should be removed as it is a requirement that applies to the entire site.

**Comment by PatrickMessierGoC** [comment]
Abandoned and closed as this is an application-wide requirement.
